terminate called after throwing an instance of 'dealii::StandardExceptions::ExcIO'
  what():  
--------------------------------------------------------
An error occurred in line <3590> of file </usr/local/src/Original/dealii-9.0.0/source/grid/grid_out.cc> in function
    void dealii::internal::{anonymous}::write_eps(const dealii::Triangulation<dim, spacedim>&, std::ostream&, const dealii::Mapping<dim, spacedim>*, const dealii::GridOutFlags::Eps<2>&, const dealii::GridOutFlags::Eps<3>&) [with int dim = 2; int spacedim = 2; std::ostream = std::basic_ostream<char>]
The violated condition was: 
    out
Additional information: 
    An input/output error has occurred. There are a number of reasons why this may be happening, both for reading and writing operations.

If this happens during an operation that tries to read data: First, you may be trying to read from a file that doesn't exist or that is not readable given its file permissions. Second, deal.II uses this error at times if it tries to read information from a file but where the information in the file does not correspond to the expected format. An example would be a truncated file, or a mesh file that contains not only sections that describe the vertices and cells, but also sections for additional data that deal.II does not understand.

If this happens during an operation that tries to write data: you may be trying to write to a file to which file or directory permissions do not allow you to write. A typical example is where you specify an output file in a directory that does not exist.
--------------------------------------------------------

/var/spool/torque/mom_priv/jobs/60.phage.hpc.union.edu.SC: line 8: 355048 Aborted                 (core dumped) ./fourthorder
